services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ultron
      - POSTGRES_USER=dani
      - POSTGRES_PASSWORD=daniadmin123
    ports:
      - 5432:5432
    volumes:
    - ./postgres_data:/var/lib/postgres/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dani@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
     - 5050:80